# Generated by Django 5.2.8 on 2025-11-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
